# ==========================================
# Tools
# ==========================================
[tools]
"github:buildpacks/pack" = "0.40.9"
gum         = "0.17.0"
prek        = "0.4.11"
rust        = "1.97.1"
# ==========================================
# Configuration
# ==========================================
[env]
RUST_BACKTRACE = "1"

[settings]
task_output = "quiet"
