# ==========================================
# Tools
# ==========================================
[tools]
"github:buildpacks/pack" = "0.40.9"
gum         = "0.17.0"
prek        = "0.4.11"
rust        = "1.97.1"
shellcheck  = "0.11.0"
shfmt       = "3.13.1"
# ==========================================
# Configuration
# ==========================================
[env]
RUST_BACKTRACE  = "1"
REGISTRY_HOST   = "ghcr.io"
REGISTRY_OWNER  = "smolppbigdreams"
IMAGE_NAME      = "ip-blocklist-generator"
# ==========================================
# Settings
# ==========================================
[settings]
task_output = "quiet"
# ==========================================
# Tools
# ==========================================
